spring.application.name=MediaTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/zrivo_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZWQ2ZWY4NDY1MjNhNmYxOGZkNzk5OTA2NjkzYzNiNyIsIm5iZiI6MTc3ODY4NTIyNC4xOSwic3ViIjoiNmEwNDk1MjhkYTYwZDU5NDNlMzc3N2VhIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.C15drRbGrnWWB1v2_fWd79XM9kvatR93vjZoUA9A7AI