CREATE TABLE IF NOT EXISTS media_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(31),
    title VARCHAR(255) NOT NULL,
    release_year INTEGER NOT NULL,
    duration_minutes INTEGER,
    directors VARCHAR(255),
    status VARCHAR(255),
    total_episodes INTEGER,
    watched_episodes INTEGER,
    series_type VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS watch_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watched_at TIMESTAMP WITHOUT TIME ZONE,
    title VARCHAR(255),
    media_type VARCHAR(255),
    minutes_watched INTEGER
    );